### ISSUE TITLE
NO WAY TO SUBMIT HOGWILD PROJECT IS IT REQUIRED OR NOT

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/react-hooks-hogwild#14]
### Canvas Link

https://learning.flatironschool.com/courses/6558/pages/hogwild-the-react-app-for-fans-of-prize-winning-pigs?module_item_id=571400

### Concern

No way to submit it. It is very unclear as to if this is a REAL assignment or just one of those THINK ABOUT IT BUT DON'T DO IT assignments. On CANVAS it says we must VIEW it which looking at the page satisfies. So is it required or not?

**Comment by lizbur10** [comment]
Hi @ckelly38 ! Thanks for bringing this to our attention - it has now been fixed. Apologies for the inconvenience 💙
